version: '3'
services:
  postgresql:
    image: postgres:14.1-alpine
    container_name: exchanger-postgres
    environment:
      - POSTGRES_DB=exchanger
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"