spring:
  application:
    name: exchange-rate-provider
  datasource:
    url: jdbc:postgresql://localhost:5432/exchanger
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9999/eureka
server:
  port: 10010
exchange:
  rate:
    nbp:
      url: http://api.nbp.pl/api